export const GET_SOF_POSTS_REQUEST = 'DATA_CONTAINER::GET_SOF_POSTS_REQUEST';
export const GET_SOF_POSTS_SUCCESS = 'DATA_CONTAINER::GET_SOF_POSTS_SUCCESS';
export const GET_SOF_POSTS_ERROR = 'DATA_CONTAINER::GET_SOF_POSTS_ERROR';
