export const GET_SOF_POSTS_REQUEST = 'DATA_CONTAINER::GET_SOF_POSTS_REQUEST';
export const GET_SOF_POSTS_SUCCESS = 'DATA_CONTAINER::GET_SOF_POSTS_SUCCESS';
export const GET_SOF_POSTS_ERROR = 'DATA_CONTAINER::GET_SOF_POSTS_ERROR';

export const GET_GH_REPOS_REQUEST = 'DATA_CONTAINER::GET_SOF_POSTS_REQUEST';
export const GET_GH_REPOS_SUCCESS = 'DATA_CONTAINER::GET_GH_REPOS_SUCCESS';
export const GET_GH_REPOS_ERROR = 'DATA_CONTAINER::GET_GH_REPOS_ERROR';

export const TOGGLE_MODAL = 'DATA_CONTAINER::TOGGLE_MODAL';
