export const GET_SOF_DETAILS_REQUEST = 'DETAILS::GET_SOF_DETAILS_REQUEST';
export const GET_SOF_DETAILS_SUCCESS = 'DETAILS::GET_SOF_DETAILS_SUCCESS';
export const GET_SOF_DETAILS_ERROR = 'DETAILS::GET_SOF_DETAILS_ERROR';

export const GET_GH_DETAILS_REQUEST = 'DETAILS::GET_GH_DETAILS_REQUEST';
export const GET_GH_DETAILS_SUCCESS = 'DETAILS::GET_GH_DETAILS_SUCCESS';
export const GET_GH_DETAILS_ERROR = 'DETAILS::GET_GH_DETAILS_ERROR';
